### ISSUE TITLE
Improving Documentation

### ISSUE THREAD

**Issue by qihaomah** [qihaomah/Distributed-System-Revision#1]
I need helps on improving the readability of README.md, it is very messy.

**Comment by chunkhang** [comment]
No problem!

**Comment by piyushsuhalkaa** [comment]
yeah sure

**Comment by piyushsuhalkaa** [comment]
@qihaomah Yeah Sure, I will do it for you

**Comment by qihaomah** [comment]
It is done by @chunkhang, thank you so much
